### ISSUE TITLE
Viết bài hướng dẫn tạo ssh key và config git

### ISSUE THREAD

**Issue by trongdung258** [tuduydongian/tuduydongian.github.io#13]

**Comment by duccoder** [comment]
Chạy lệnh để gen keys:

```
ssh-keygen -t rsa -b 4096 -C "your_email@example.com"
```

Tạo ra cặp public - private key, backup để xài cho lần sau  cài lại hệ điều hành.

- Private key (`id_rsa`) thả vào thư mục `.ssh` ở thư mục home của user (`home/you/.ssh/id_rsa`) và chmod 400
- Public key ai xin thì cho

Ref: https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/

@trongdung258 Em thêm mắm thêm muối vào rồi update vào bài viết của em luôn khỏi loãng
